### ISSUE TITLE
ReferenceError: MailParser is not defined

### ISSUE THREAD

**Issue by landland** [BashtonLtd/meteor-mailparser#1]
Trying out this package on Meteor 0.6.5 and got stuck with the error:
ReferenceError: MailParser is not defined

Code is the example from the original node MailParser package

var mailparser = new MailParser();

var email = "From: 'Sender Name' sender@example.com\r\n"+
            "To: 'Receiver Name' receiver@example.com\r\n"+
            "Subject: Hello world!\r\n"+
            "\r\n"+
            "How are you today?";

// setup an event listener when the parsing finishes
mailparser.on("end", function(mail_object){
    console.log("From:", mail_object.from); //[{address:'sender@example.com',name:'Sender Name'}]
    console.log("Subject:", mail_object.subject); // Hello world!
    console.log("Text body:", mail_object.text); // How are you today?
});

// send the email source to the parser
mailparser.write(email);
mailparser.end();

**Comment by dwatson** [comment]
Hi,

Change your code to:

``` javascript
var parser = new mailparser.MailParser();

var email = "From: 'Sender Name' sender@example.com\r\n"+
"To: 'Receiver Name' receiver@example.com\r\n"+
"Subject: Hello world!\r\n"+
"\r\n"+
"How are you today?";

// setup an event listener when the parsing finishes
parser.on("end", function(mail_object){
console.log("From:", mail_object.from); //[{address:'sender@example.com',name:'Sender Name'}]
console.log("Subject:", mail_object.subject); // Hello world!
console.log("Text body:", mail_object.text); // How are you today?
});

// send the email source to the parser
parser.write(email);
parser.end();
```

The package exports the entire node module as mailparser.

**Comment by landland** [comment]
Awesome, thanks. Perhaps a small usage example would be perfect. Cheers.
